config/routes.rb
Rails.application.routes.draw do
  resources :conversors do
    collection do
      get 'get_categories'
      get 'get_exchange/:coin', :action => :get_exchange
    end
  end
  root 'conversors#index'

end

app/models/conversor.rb
require 'open-uri'
require 'json'


class Conversor < ActiveRecord::Base
  @@API_KEY = "86a2d0814613df7f6459de5656a60970"

  def hello_api
    @@API_KEY
  end

  def get_exchange
    stream = open(
      "http://apilayer.net/api/historical?"+
      "&date=2016-11-29"+
      "&currencies=EUR,BRL,ARS"+
      "&access_key="+@@API_KEY
      )
    data = stream.read
    json = JSON.parse(data)
  end

  def to_brl(usdbrl,currency)
    return usdbrl / currency
  end

  def get_exchange_by_date(date)
    stream = open(
      "http://apilayer.net/api/historical?"+
      "&date="+date+
      "&currencies=EUR,BRL,ARS"+
      "&access_key="+@@API_KEY
      )
    data = stream.read
    json = JSON.parse(data)
    return json
  end

  def get_exchange_by_coin_and_date(coin,date)
    json = get_exchange_by_date(date)
    if coin == "USD" then return json['quotes']['USDBRL'] end
    return to_brl(json['quotes']['USDBRL'],json['quotes']['USD'+coin])
  end

  def get_dates(start)
    d = Date.parse(start.gsub(/, */, '-'))
    d = d-6
    dates = []
    7.times do
      dates.append(d.to_s)
      d += 1
    end
    return dates
  end

  def get_exchange_formatted(coin)
    dates = get_dates(Date.today.to_s)
    exchanges = []
    for date in dates do
      exchanges.append(get_exchange_by_coin_and_date(coin,date))
    end
    return {name: coin, data: exchanges}
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/conversors_controller.rb
class ConversorsController < ApplicationController
  before_action :set_conversor, only: [:show, :edit, :update, :destroy]

  # GET /conversors
  # GET /conversors.json
  def index
    @conversors = Conversor.all
  end

  # GET /conversors/1
  # GET /conversors/1.json
  def show
  end

  # GET /conversors/new
  def new
    @conversor = Conversor.new
  end

  # GET /conversors/1/edit
  def edit
  end

  # POST /conversors
  # POST /conversors.json
  def create
    @conversor = Conversor.new(conversor_params)

    respond_to do |format|
      if @conversor.save
        format.html { redirect_to @conversor, notice: 'Conversor was successfully created.' }
        format.json { render :show, status: :created, location: @conversor }
      else
        format.html { render :new }
        format.json { render json: @conversor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversors/1
  # PATCH/PUT /conversors/1.json
  def update
    respond_to do |format|
      if @conversor.update(conversor_params)
        format.html { redirect_to @conversor, notice: 'Conversor was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversor }
      else
        format.html { render :edit }
        format.json { render json: @conversor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversors/1
  # DELETE /conversors/1.json
  def destroy
    @conversor.destroy
    respond_to do |format|
      format.html { redirect_to conversors_url, notice: 'Conversor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def get_categories
    @conversor = Conversor.new
    render :json => @conversor.get_dates(Date.today.to_s)
  end

  def get_exchange
    @conversor = Conversor.new
    render :json => @conversor.get_exchange_formatted(params[:coin])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversor
      @conversor = Conversor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversor_params
      params.fetch(:conversor, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversors_helper.rb
module ConversorsHelper
end

app/views/conversors/_form.html.erb
<%= form_for(@conversor) do |f| %>
  <% if @conversor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@conversor.errors.count, "error") %> prohibited this conversor from being saved:</h2>

      <ul>
      <% @conversor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/conversors/edit.html.erb
<h1>Editing Conversor</h1>

<%= render 'form' %>

<%= link_to 'Show', @conversor %> |
<%= link_to 'Back', conversors_path %>

app/views/conversors/index.html.erb
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<p id="notice"><%= notice %></p>

<h1>Bem vindo ao Inncurrency,</h1>
<h2>Sua plataforma de conversão de moedas.</h2>

<br>
<h3>Escolha sua moeda</h3>
<!--<%= link_to 'Dólar (USD)', new_conversor_path, :class => "btn btn-primary" %>
<%= link_to 'Euro (EUR)', new_conversor_path, :class => "btn btn-success" %>
<%= link_to 'Peso Argentino (ARS)', new_conversor_path, :class => "btn btn-warning" %>-->
<button type="button" name="button1" class="btn btn-info" onclick="get_coin('USD')">Dólar (USD)</button>
<button type="button" name="button2" class="btn btn-success" onclick="get_coin('EUR')">Euro (EUR)</button>
<button type="button" name="button3" class="btn btn-warning" onclick="get_coin('ARS')">Peso Argentino (ARS)</button>

<div id="container">

</div>

app/views/conversors/new.html.erb
<h1>New Conversor</h1>

<%= render 'form' %>

<%= link_to 'Back', conversors_path %>

app/views/conversors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_conversor_path(@conversor) %> |
<%= link_to 'Back', conversors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inncurrency</title>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>
<div class="container-fluid">
  <%= yield %>
</div>

</body>
</html>